global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Enable remote write receiver
remote_write:
  - url: http://localhost:9090/api/v1/write

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
